name: Generate Snake
on:
  schedule:
    # Executa a cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz o download do repositório
      - uses: actions/checkout@v2

      # Gera a cobra com base nas suas contribuições
      - uses: Platane/snk@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Configurações para gerar o gráfico da cobra
          output: dist/github-snake.svg
          user_name: chaywilliam

      # Publica o arquivo gerado no branch 'output'
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
